name: pytest_env
channels:
  - bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - amply=0.1.6=pyhd8ed1ab_0
  - arpack=3.9.1=nompi_h77f6705_101
  - biopython=1.84=py39hd3abc70_0
  - blast=2.16.0=hc155240_3
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.3=hb9d3cd8_1
  - ca-certificates=2024.8.30=hbcca054_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - coin-or-cbc=2.10.12=h8b142ea_1
  - coin-or-cgl=0.60.9=h1d3f3f2_0
  - coin-or-clp=1.17.10=h07f2a63_0
  - coin-or-osi=0.108.11=h6514dde_1
  - coin-or-utils=2.11.12=h99da652_1
  - coincbc=2.10.12=1_metapackage
  - colorama=0.4.6=pyhd8ed1ab_1
  - curl=8.10.1=hbbe4b11_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - docutils=0.21.2=pyhd8ed1ab_1
  - entrez-direct=22.4=he881be0_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - expat=2.6.4=h5888daf_0
  - fastcluster=1.2.6=py39hec4eb1f_4
  - fraggenescan=1.30=h470a237_2
  - freetype=2.12.1=h267a509_2
  - gdbm=1.18=h0a1914f_2
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - glpk=5.0=h445213a_0
  - gmp=6.3.0=hac33072_2
  - hmmer=3.4=hdbdd923_2
  - iniconfig=2.0.0=pyhd8ed1ab_1
  - isescan=1.7.2.3=h031d066_2
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py39h74842e3_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - lerc=4.0.0=h27087fc_0
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libblas=3.9.0=25_linux64_openblas
  - libcblas=3.9.0=25_linux64_openblas
  - libcurl=8.10.1=hbbe4b11_0
  - libdeflate=1.21=h4bc722e_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.7=hd590300_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=25_linux64_openblas
  - liblapacke=3.9.0=25_linux64_openblas
  - liblzma=5.6.3=hb9d3cd8_0
  - liblzma-devel=5.6.3=hb9d3cd8_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.28=pthreads_h94d23a6_1
  - libpng=1.6.44=hadc24fc_0
  - libsqlite=3.47.0=hadc24fc_1
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtiff=4.7.0=h6565414_0
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.5=h0d44e9d_1
  - libzlib=1.3.1=hb9d3cd8_2
  - longestrunsubsequence=1.0.1=py_0
  - matplotlib-base=3.3.4=py39h2fa2bec_0
  - mummer=3.23=pl5321hdbdd923_20
  - ncbi-vdb=3.1.1=h4ac6f70_2
  - ncurses=6.5=he02047a_1
  - numpy=1.26.4=py39h474f0d3_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openssl=3.4.0=hb9d3cd8_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.0.3=py39h40cae4c_1
  - perl=5.32.1=7_hd590300_perl5
  - perl-archive-tar=2.40=pl5321hdfd78af_0
  - perl-carp=1.50=pl5321hd8ed1ab_0
  - perl-common-sense=3.75=pl5321hd8ed1ab_0
  - perl-compress-raw-bzip2=2.201=pl5321hbf60520_0
  - perl-compress-raw-zlib=2.202=pl5321hadc24fc_0
  - perl-encode=3.21=pl5321hb9d3cd8_1
  - perl-exporter=5.74=pl5321hd8ed1ab_0
  - perl-exporter-tiny=1.002002=pl5321hd8ed1ab_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-io-compress=2.201=pl5321hdbdd923_3
  - perl-io-zlib=1.14=pl5321hdfd78af_0
  - perl-json=4.10=pl5321hdfd78af_1
  - perl-json-xs=4.03=pl5321h4ac6f70_3
  - perl-list-moreutils=0.430=pl5321hdfd78af_0
  - perl-list-moreutils-xs=0.430=pl5321h031d066_3
  - perl-parent=0.242=pl5321hd8ed1ab_0
  - perl-pathtools=3.75=pl5321hb9d3cd8_1
  - perl-scalar-list-utils=1.68=pl5321hb9d3cd8_0
  - perl-storable=3.15=pl5321hb9d3cd8_0
  - perl-types-serialiser=1.01=pl5321hdfd78af_0
  - pillow=11.0.0=py39h538c539_0
  - pip=24.3.1=pyh8b19718_0
  - pluggy=1.5.0=pyhd8ed1ab_1
  - psutil=6.1.0=py39h8cd3c5a_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pulp=2.8.0=py39hf3d152e_0
  - pyparsing=3.2.0=pyhd8ed1ab_2
  - pysam=0.22.1=py39h61809e1_2
  - pytest=8.3.3=pyhd8ed1ab_0
  - python=3.9.21=h9c0c6dc_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-igraph=0.11.8=py39hb479397_0
  - python-tzdata=2024.2=pyhd8ed1ab_1
  - python_abi=3.9=5_cp39
  - pytz=2024.2=pyhd8ed1ab_1
  - readline=8.2=h8228510_1
  - rpsbproc=0.5.0=h6a68c12_1
  - scipy=1.13.1=py39haf93ffa_0
  - setuptools=75.6.0=pyhff2d567_1
  - six=1.16.0=pyhd8ed1ab_1
  - sqlite=3.47.0=h9eae976_1
  - syri=1.6.3=py39he10ea66_1
  - texttable=1.7.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.2.1=pyhd8ed1ab_1
  - tornado=6.4.2=py39h8cd3c5a_0
  - tzdata=2024b=hc8b5060_0
  - wget=1.21.4=hda4d442_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libx11=1.8.10=h4f16b4b_1
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xz=5.6.3=hbcc6ac9_0
  - xz-gpl-tools=5.6.3=hbcc6ac9_0
  - xz-tools=5.6.3=hb9d3cd8_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.6=ha6fb4c9_0
